<?xml version="1.0" encoding="UTF-8"?><testrun name="EncerradorDeLeilaoTest" project="teste-de-unidade" tests="4" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.246">
    <testcase name="naoDeveEncerrarLeiloesCasoNaoHajaNenhum" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.143"/>
    <testcase name="naodeveEncerrarLeiloesQueComecaramOntem" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.018"/>
    <testcase name="deveEncerrarLeiloesQueComecaramUmaSemanaAntes" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.054"/>
    <testcase name="deveAtualizarLeiloesEncerrados" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.031">
      <failure>org.mockito.exceptions.verification.TooManyActualInvocations: 
repositorioDeLeiloes.atualiza(
    br.com.caelum.leilao.dominio.Leilao@566776ad
);
Wanted 1 time:
-&gt; at br.com.caelum.leilao.servico.EncerradorDeLeilaoTest.deveAtualizarLeiloesEncerrados(EncerradorDeLeilaoTest.java:93)
But was 2 times. Undesired invocation:
-&gt; at br.com.caelum.leilao.servico.EncerradorDeLeilao.encerra(EncerradorDeLeilao.java:27)

	at br.com.caelum.leilao.servico.EncerradorDeLeilaoTest.deveAtualizarLeiloesEncerrados(EncerradorDeLeilaoTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
  </testsuite>
</testrun>
