<?xml version="1.0" encoding="UTF-8"?><testrun name="EncerradorDeLeilaoTest" project="teste-de-unidade" tests="8" started="8" failures="0" errors="1" ignored="0">
  <testsuite name="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.288">
    <testcase name="naoDeveEncerrarLeiloesCasoNaoHajaNenhum" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.124"/>
    <testcase name="deveContinuarAExecucaoMesmoQuandoEnviadorDeEmaillFalha" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.027">
      <error>org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: java.lang.Exception
	at br.com.caelum.leilao.servico.EncerradorDeLeilaoTest.deveContinuarAExecucaoMesmoQuandoEnviadorDeEmaillFalha(EncerradorDeLeilaoTest.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</error>
    </testcase>
    <testcase name="deveEnviarEmailAposAtualizarLeiloesEncerrados" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.061"/>
    <testcase name="naodeveEncerrarLeiloesQueComecaramOntem" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.003"/>
    <testcase name="naoDeveEncerrarLeiloesQueComecaramMenosDeUmaSemanaAtras" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.016"/>
    <testcase name="deveEncerrarLeiloesQueComecaramUmaSemanaAntes" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.022"/>
    <testcase name="deveAtualizarLeiloesEncerrados" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.012"/>
    <testcase name="deveContinuarAExecucaoMesmoQuandoDaoFalha" classname="br.com.caelum.leilao.servico.EncerradorDeLeilaoTest" time="0.023"/>
  </testsuite>
</testrun>
